# Generated by Django 3.0.5 on 2020-07-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('name', models.CharField(max_length=17)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.CharField(max_length=10)),
                ('nameofmem', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgfrom', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('msgtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=10)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Member')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Message')),
            ],
        ),
    ]
